const CFG=window.BARBEARIA_CONFIG;let db=null,currentUser=null;const $=s=>document.querySelector(s);const pad=n=>String(n).padStart(2,"0");const today=()=>{const d=new Date();return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};function ready(){return window.supabase&&CFG.SUPABASE_URL&&!CFG.SUPABASE_URL.includes("COLE_AQUI")}if(ready())db=supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_ANON_KEY);
async function load(){if(!db){$("#loginMsg").textContent="Configure o config.js com as credenciais do Supabase.";return}const {data:{session}}=await db.auth.getSession();if(session){currentUser=session.user;showDash()}else $("#login").classList.remove("hidden")}
function showDash(){$("#login").classList.add("hidden");$("#dashboard").classList.remove("hidden");$("#adminDate").value=today();$("#todayLabel").textContent=new Date($("#adminDate").value+"T12:00:00").toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"});loadSettings();loadAppointments()}
async function loadSettings(){const {data}=await db.from("business_settings").select("*").eq("id",1).maybeSingle();if(data){$("#closeTime").value=data.close_time;$("#toggleOpen").classList.toggle("on",data.enabled)}}
async function loadAppointments(){const date=$("#adminDate").value;const {data,error}=await db.from("appointments").select("*").eq("appointment_date",date).order("start_time");const list=$("#adminList");if(error){list.innerHTML=`<div class="appointment"><div>Erro: ${error.message}</div></div>`;return}if(!data?.length){list.innerHTML='<div class="appointment"><div>Nenhum agendamento para este dia.</div></div>';return}list.innerHTML=data.map(a=>`<div class="appointment ${a.status}"><div class="appt-time">${a.start_time}<small>– ${a.end_time}</small></div><div class="appt-main"><b>${a.customer_name} · ${a.service_name}</b><small>${a.customer_phone} · R$ ${a.price}${a.note?` · ${a.note}`:""}</small><span class="badge ${a.status}">${a.status==="confirmed"?"CONFIRMADO":"PENDENTE"}</span></div><div class="appt-actions">${a.status!=="confirmed"?`<button class="btn-mini confirm" onclick="setStatus('${a.id}','confirmed')">✓ Confirmar</button>`:""}<a class="btn-mini" target="_blank" href="https://wa.me/${a.customer_phone.replace(/\D/g,"")}?text=${encodeURIComponent("Olá, "+a.customer_name+"! Seu horário na Barbearia Silva foi "+(a.status==="confirmed"?"confirmado":"registrado")+" para "+a.start_time+".") }">WhatsApp</a><button class="btn-mini reject" onclick="setStatus('${a.id}','cancelled')">Cancelar</button></div></div>`).join("")}
async function setStatus(id,status){const {error}=await db.from("appointments").update({status}).eq("id",id);if(error)alert(error.message);loadAppointments()}
$("#loginBtn").onclick=async()=>{const {error}=await db.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error)$("#loginMsg").textContent=error.message;else showDash()}
$("#logout").onclick=()=>db.auth.signOut().then(()=>location.reload());
$("#refresh").onclick=loadAppointments;$("#adminDate").onchange=()=>{$("#todayLabel").textContent=new Date($("#adminDate").value+"T12:00:00").toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"});loadAppointments()};
$("#toggleOpen").onclick=()=>$("#toggleOpen").classList.toggle("on");
$("#saveHours").onclick=async()=>{const enabled=$("#toggleOpen").classList.contains("on");const close=$("#closeTime").value;const {error}=await db.from("business_settings").update({enabled,close_time:close}).eq("id",1);alert(error?"Erro ao salvar: "+error.message:"Horário/abertura atualizados.");};
load();